### ISSUE TITLE
登录出现无法勾选隐私协议问题

### ISSUE THREAD

**Issue by 961905** [LambdaExpression/ChinaTelecomMonitor#1]
![9DD4F293-BC41-43FF-981F-0F55A1763940](https://user-images.githubusercontent.com/32889052/167545457-c7b9b76b-bfc3-4c90-ab8c-6160516e2237.jpeg)

**Comment by LambdaExpression** [comment]
电信页面改版，变成默认勾选隐私协议了。我先修改了代码，自动打了一个包，你可以现在暂时先使用这个试一下 [China_Telecom_Monitor_amd64](https://github.com/LambdaExpression/ChinaTelecomMonitor/suites/6441139878/artifacts/235838984)，稍后我再把它发布到正式的版本

https://github.com/LambdaExpression/ChinaTelecomMonitor/actions/runs/2298701263

**Comment by 961905** [comment]
感谢，可以了

**Comment by LambdaExpression** [comment]
ok，那我先把问题关了
