### ISSUE TITLE
输入服务器ip:9222 提示Inspectable WebContents WARNING: This page is deprecated and will be removed by m96. Please use  instead. Use crbug.com/1232509 for comments, questions and feedback. about:blank

### ISSUE THREAD

**Issue by Zhangtaiy** [LambdaExpression/ChinaTelecomMonitor#14]

**Comment by LambdaExpression** [comment]
![image](https://user-images.githubusercontent.com/17667040/182054663-7ddf9e9c-5839-489d-838f-b767a66b3ca0.png)

9222 默认是容器端口。访问用的端口默认是 8080

**Comment by LambdaExpression** [comment]
访问还有问题吗？没有的话，我近期就先把问题关了

**Comment by Zhangtaiy** [comment]
老哥8080打不开

**Comment by Zhangtaiy** [comment]
老哥方便留个tg联络方式吗

**Comment by LambdaExpression** [comment]
可以把 
- 启动命令
- ./data/log/stdout.log 的日志
- ./data/login/ 目录下的图片

发出来，我看一下吗？有问题可以先在issues沟通解决，留下记录也能方便有相同问题的用户

**Comment by Zhangtaiy** [comment]
![image](https://user-images.githubusercontent.com/68043299/182523047-5201903b-9623-4853-919b-66cb628732b1.jpeg)老哥，我是纯新手，希望能加个联系方式，@zhang5202

**Comment by Zhangtaiy** [comment]
![image](https://user-images.githubusercontent.com/68043299/182524666-275e2d10-aa0b-41eb-8ca6-8c44bf9b5207.png)

**Comment by LambdaExpression** [comment]
你把 ./data/login/  目录下的几张截图上传上来。大概率是账号密码写错了

**Comment by Zhangtaiy** [comment]
![image](https://user-images.githubusercontent.com/68043299/182555744-339e0cfe-8a02-4644-8895-e2eecadf5fa7.png)
![image](https://user-images.githubusercontent.com/68043299/182556820-f1d041eb-753d-4b6b-a174-dfe323037898.png)

是这个吗？

**Comment by Zhangtaiy** [comment]
![image](https://user-images.githubusercontent.com/68043299/182557709-aa6f2249-12b5-4cb0-be4f-4e44ff32e827.png)

**Comment by LambdaExpression** [comment]
> ![image](https://user-images.githubusercontent.com/68043299/182555744-339e0cfe-8a02-4644-8895-e2eecadf5fa7.png) ![image](https://user-images.githubusercontent.com/68043299/182556820-f1d041eb-753d-4b6b-a174-dfe323037898.png)
> 
> 是这个吗？

嗯，你先下载到本地，用图片浏览器打开看一下吧

**Comment by LambdaExpression** [comment]
> ![image](https://user-images.githubusercontent.com/68043299/182557709-aa6f2249-12b5-4cb0-be4f-4e44ff32e827.png)

日志的话，建议整个文件上传，或者截取看见有异常抛出的部分。这样的日志截图是看不出问题的

**Comment by Zhangtaiy** [comment]
![image](https://user-images.githubusercontent.com/68043299/182572100-a7d0a927-0373-402a-ba82-92621d12badd.png)
![image](https://user-images.githubusercontent.com/68043299/182572139-e262232c-5ab2-4993-a4ae-e9bbddbd94b1.png)
[stdout.log](https://github.com/LambdaExpression/ChinaTelecomMonitor/files/9249849/stdout.log)

**Comment by LambdaExpression** [comment]
这个日志文件是完整的吗？我没看到日志里面有对应的错误

**Comment by LambdaExpression** [comment]
你的启动命令可以也发一下吗？

**Comment by LambdaExpression** [comment]
你先启动应用3分钟后，再查看一下日志和登录截图。你这个可能太急了，没得到完整的日志就上传了

**Comment by Zhangtaiy** [comment]
[stdout.log](https://github.com/LambdaExpression/ChinaTelecomMonitor/files/9250395/stdout.log)
您看下这个。
./China_Telecom_Monitor_amd64 --prot 8081 --dockerProt 9222 --username '15534041333' --password '468998'

**Comment by LambdaExpression** [comment]
> [stdout.log](https://github.com/LambdaExpression/ChinaTelecomMonitor/files/9250395/stdout.log) 您看下这个。 ./China_Telecom_Monitor_amd64 --prot 8081 --dockerProt 9222 --username '* * * * * *' --password ' * * * * *'

不好意思，为了你的信息安全，我善自修改了你的评论，加密了你的账号密码。

我说了一下我发现的点

1.你的账号密码错误了。你现在如果查看服务器内的 ./data/login/03.png 应该也是提示和下面图片一样，提示密码错误。你可以先访问一下 https://e.189.cn/wap/index.do 测试一下你的账号。

![image](https://user-images.githubusercontent.com/17667040/182749296-6e4e7baf-16b8-46bb-85c9-6bc11cb8d7f0.png)

2. 你启动命令使用了 “--prot 8081 ” 指定了访问端口为 8081

3. 为了你的账号安全，请优先修改一下密码

**Comment by Zhangtaiy** [comment]
感谢，我刚才已经更改了密码了，但是输入新的账号密码还是打不开8081，只是用新的账号密码登录会提示，错误次数过多，输入屏幕上的验证码
[stdout.log](https://github.com/LambdaExpression/ChinaTelecomMonitor/files/9256359/stdout.log)

**Comment by Zhangtaiy** [comment]
![image](https://user-images.githubusercontent.com/68043299/182759665-e219578d-e86e-4b1f-bae3-18af1ad4b07d.png)
您好，貌似登录成功了，但是8081 依旧打不开。。。。

**Comment by LambdaExpression** [comment]
在服务器上执行 `curl http://127.0.0.1:8081/show/flow` 这个命令能正常返回数据吗？

**Comment by Zhangtaiy** [comment]
> 在服务器上执行`curl http://127.0.0.1:8081/show/flow`这个命令能正常返回数据吗？

提示拒绝连接
<img width="307" alt="微信截图_20220804124350" src="https://user-images.githubusercontent.com/68043299/182764944-755defa3-3088-41a2-ba49-0c523ae69f5f.png">
，

**Comment by LambdaExpression** [comment]
`ps -ef | grep  China_`
`netstat -natp | grep China_`

输入这两个命令我看一下服务器进程。有敏感信息的话，注意打一下码

**Comment by Zhangtaiy** [comment]
![image](https://user-images.githubusercontent.com/68043299/182774559-2889844a-73ce-43a3-a5be-2e46cba5e247.png)
不知道怎样挂后台。。。。

**Comment by LambdaExpression** [comment]
`nohup ./China_Telecom_Monitor_amd64 --prot 8081 --dockerProt 9222 --username '* * * * * *' --password ' * * * * *' >/dev/null &`

挂后台的方式有很多种，你可以先学习一下其中一种 nohup 命令，用上面这种写法就能保证应用后台运行不挂断

**Comment by Zhangtaiy** [comment]
老哥貌似成功了，现在断开SSH 也可以打开8081的端口了，
但是提示
Not Found
 SSH 输入curl http://127.0.0.1:8081/show/flow
![image](https://user-images.githubusercontent.com/68043299/182780933-83c196a2-d29e-486b-985b-d3aa23322ddd.png)
也能出现返回数据了

**Comment by Zhangtaiy** [comment]
感谢老哥， 已经全部闹好了。可以关闭提问了。

**Comment by LambdaExpression** [comment]
👌，那我就先把问题关了
