### ISSUE TITLE
不知道电信是否更换接口

### ISSUE THREAD

**Issue by 961905** [LambdaExpression/ChinaTelecomMonitor#15]
最近一段时间日志显示查询失败，目前无法使用，不知道是否我一个人这样。

**Comment by LambdaExpression** [comment]
我这边没有提示有问题，可以提供一下你现在使用的版本和查询失败的日志吗？

以及你可以先试一下手动登录一下 [https://e.189.cn/wap/index.do](https://e.189.cn/wap/index.do) ，之后再使用应用查询看一下是否还存在问题。
电信接口在被频繁登录后，会要求手动输入验证码，触发账号这种状态时也会出现无法正常查询的问题，不过只要手动登录输入过一次验证就能解除这种严格的账号状态了

**Comment by 961905** [comment]
![BB8437B0-AA35-4204-939D-20427D43260D](https://user-images.githubusercontent.com/32889052/186649636-a141348c-89de-4d72-acda-e7074c60d59e.png)       


目前日志就是显示这样，来了ck生成时间都是正常的，登录截图也是正常。

**Comment by LambdaExpression** [comment]
我先确认一下，你现在用的是最新版本吗？因为老版本有个登录不稳定的问题，有一定概率会出现你这种情况

**Comment by 961905** [comment]
目前是1.06，我更新试试

**Comment by 961905** [comment]
已测试新版本，依旧同样日志

**Comment by LambdaExpression** [comment]
可以试一下把./data目录删除，启动应用，再发一下你目录下的 ./data/login/01.png、./data/login/02.png 、 ./data/login/03.png 这三张截图和完整的日志文件吗？（注意隐藏敏感信息）

**Comment by 961905** [comment]
https://airportal.cn/725328/HuR1xuJcY0

**Comment by LambdaExpression** [comment]
我反复调试了一下，都无法复现你的情况。不过我发现你调用电信接口后返回的结果有点奇怪。


*https://e.189.cn/store/user/balance_new.do 接口为例*
你的日志情况：
![image](https://user-images.githubusercontent.com/17667040/186801046-33e8acb0-cc17-4259-8efa-f9f66f515b97.png)
正常未登录情况：
![image](https://user-images.githubusercontent.com/17667040/186801175-b6bbe3b6-8145-4e87-a85f-4cdefdd4baef.png)
正常已登录情况：
![image](https://user-images.githubusercontent.com/17667040/186801256-2aa23612-f18a-4908-9ddc-a2dcc99f6d33.png)



*https://e.189.cn/store/wap/flowPackage.do 接口为例*
你的日志情况：
![image](https://user-images.githubusercontent.com/17667040/186800971-0ce36bf5-ef97-4408-a885-dbd6501aa945.png)
正常未登录情况：
![image](https://user-images.githubusercontent.com/17667040/186801098-db6a121b-aa2e-4268-823c-330aeaa75ced.png)
正常已登录情况：
![image](https://user-images.githubusercontent.com/17667040/186801133-43c7d880-a229-46f3-98d0-a706ee083070.png)


结合登录截图的分析，你应该已经登录成功，但账号的数据有问题，导致电信接口查询时出现了异常无法正常统计数据返回 ![image](https://user-images.githubusercontent.com/17667040/186801732-ac1b9cc6-6073-4205-ab3b-4af3861101e8.png) msg 的 ”default query fail“ 可能就接口异常抛出来的信息。

我建议你先试一下下载 [电信营业厅](https://apps.apple.com/cn/app/%E7%94%B5%E4%BF%A1%E8%90%A5%E4%B8%9A%E5%8E%85-%E6%96%B0%E4%BA%BA%E9%A2%86%E8%B1%AA%E5%8D%8E%E5%A4%A7%E7%A4%BC%E5%8C%85/id513836029) APP 试一下，如果 APP 也无法正常查询流量，那就能确定是电信那边有问题了

**Comment by 961905** [comment]
我感觉也是电信接口的问题，所以才来问问电信是否更换了接口，然后昨天下午接口又突然的能返回结果了

**Comment by 961905** [comment]
电信APP一直都是正常的

**Comment by 961905** [comment]
然后现在，流量显示正常了，话费显示0

**Comment by LambdaExpression** [comment]
#16 昨天有其他用户反馈遇到了和你一样的日志情况。既然你说这电信的接口会突然又正常了，那就能确定是电信问题。不过这让就变得很被动了

**Comment by LambdaExpression** [comment]
请问还有其他问题吗？没有的话，我之后就先把问题关了
