### ISSUE TITLE
数据无法正常显示，全都为“0

### ISSUE THREAD

**Issue by Mrvivi** [LambdaExpression/ChinaTelecomMonitor#16]

**Comment by Mrvivi** [comment]
部署好之后，进http://x.x.x.x:8081/show/flow ，结果为：{"code":200,"data":{"id":0,"username":"","use":0,"total":0,"generalUse":0,"generalTotal":0,"specialUse":0,"specialTotal":0,"balance":0,"voiceUsage":0,"voiceAmount":0,"createTime":"","items":null}}

我看过data/login里面的三张图片，是正常的，然后我把data/log里面的日志放在附件你帮我看下
[stdout.log](https://github.com/LambdaExpression/ChinaTelecomMonitor/files/9429818/stdout.log)
。

**Comment by LambdaExpression** [comment]
可以试一下用电信的app，看能不能正常查询到流量信息吗？

**Comment by Mrvivi** [comment]
其实之前用了很长一端时间它都是好的，也不知道什么时候就不正常显示了，也重新安装了。你看，以下三处数值是不一样的 ：
<img width="538" alt="Snipaste_2022-08-26_15-49-28" src="https://user-images.githubusercontent.com/49402255/186851206-e6b19102-388b-49ea-8bfa-0e9d4feb1f63.png">

![Screenshot_20220826_154153](https://user-images.githubusercontent.com/49402255/186851248-4affb448-d2d6-48b7-9d3e-dc740851906a.jpg)

![IMG_5183](https://user-images.githubusercontent.com/49402255/186851276-c6668ac2-ca7b-406f-97e7-6290bf788bcc.jpeg)

**Comment by Mrvivi** [comment]
我还测试出来了一个事情，教程里面获取余量信息的叫做天翼账号，我用电信营业厅这个APP的这套账号密码也是可以获取到余量信息的，也就是说这两套账号密码是独立的，都可以用到此教程。

**Comment by LambdaExpression** [comment]
> 其实之前用了很长一端时间它都是好的，也不知道什么时候就不正常显示了，也重新安装了。你看，以下三处数值是不一样的 ： <img alt="Snipaste_2022-08-26_15-49-28" width="538" src="https://user-images.githubusercontent.com/49402255/186851206-e6b19102-388b-49ea-8bfa-0e9d4feb1f63.png">
> 
> ![Screenshot_20220826_154153](https://user-images.githubusercontent.com/49402255/186851248-4affb448-d2d6-48b7-9d3e-dc740851906a.jpg)
> 
> ![IMG_5183](https://user-images.githubusercontent.com/49402255/186851276-c6668ac2-ca7b-406f-97e7-6290bf788bcc.jpeg)

这几张照片是同一个账号？

**Comment by LambdaExpression** [comment]
> 我还测试出来了一个事情，教程里面获取余量信息的叫做天翼账号，我用电信营业厅这个APP的这套账号密码也是可以获取到余量信息的，也就是说这两套账号密码是独立的，都可以用到此教程。

你的意思是你用了A手机号码的天翼账号和A手机号码的电信营业厅账号，均可通过 ChinaTelecomMonitor 获取到流量信息？

**Comment by Mrvivi** [comment]
嗯，是的。我展示的三张照片是同一个手机账号的数据。对，就是同一个手机号码，用天翼账号的手机号码+密码以及用电信营业厅APP的手机号码+密码都可以在此教程里面获取到流量话费信息，可惜我获取到的都是不正确数据，跟实际数据不相符。而且小组件上面显示的最后更新时间也延迟严重，比如我12:51分执行命令启动程序，打开手机小组件，它显示最后更新时间是03:20，或者是其他时间，并不是跟现在时间非常接近的时间。

**Comment by LambdaExpression** [comment]
```
curl http://127.0.0.1:8081/show/flowPackage
curl http://127.0.0.1:8081/show/detail
```
应用中有两个完全返回电信数据的接口，本来是用于给有需求的用户进行二次开发时使用的。不用你也可以检查一下这个两个接口的数据中是否符合你的真实流量使用情况。不过这两个接口只是转发了一下电信的接口，我也没有找到对应的文档，所以参数阅读时需要自己联想一下。

关于时间的话，默认返回的时间是服务器时间，可能也需要检查一下服务器时间是否正常

**Comment by LambdaExpression** [comment]
请问还有其他问题吗？没有的话，我之后就先把问题关了

**Comment by Mrvivi** [comment]
> 请问还有其他问题吗？没有的话，我之后就先把问题关了

我操作不成功，还是显示不正常，我不得已放弃了，虽然喜欢这个组件。关了吧，老板
