### ISSUE TITLE
数据怎样可以自动更新呢？

### ISSUE THREAD

**Issue by Zhangtaiy** [LambdaExpression/ChinaTelecomMonitor#17]
![image](https://user-images.githubusercontent.com/68043299/186822576-d7786612-fbb2-43b3-80f8-4357187fdf09.jpeg)
更新日期一直是那一天

**Comment by LambdaExpression** [comment]
这是服务挂了导致组件一直获取不到最新的数据。重新启动一下你的服务应该就可以了

**Comment by Zhangtaiy** [comment]
那如果我想在我的服务器中卸载 应该用什么命令呢？

**Comment by LambdaExpression** [comment]
直接删除应用文件和对应的./data目录就好了
