### ISSUE TITLE
登录问题（应该是获取不了cookie文件导致的）（已解决#docker容器无法连接上网导致登录失败#）

### ISSUE THREAD

**Issue by WM9116** [LambdaExpression/ChinaTelecomMonitor#18]
大大你好，打扰了，换了一台新服务器（Ubuntu 20.04），
[stdout.log](https://github.com/LambdaExpression/ChinaTelecomMonitor/files/9431990/stdout.log)
登录出现问题（应该是获取不了cookie文件导致的），并且只能写入3.png。
替换了老服务器的 data 文件夹，可以正常运行，但到了cookie失效时问题复现。大大能看出问题所在吗？谢谢！！！

**Comment by LambdaExpression** [comment]
可以发一下  ./data/login/ 下的三张png图片吗？

**Comment by WM9116** [comment]
大大，仅有这一张
![03](https://user-images.githubusercontent.com/65065448/186879418-dea5842d-7cf2-4c0a-9390-7101bda7abbf.png)

**Comment by LambdaExpression** [comment]
应该是docker容器无法连接上网，导致登录失败。

我没有ubuntu的环境，你试一下下面链接的这种方式能不能解决
https://www.jianshu.com/p/d0a4a826ab9a

**Comment by WM9116** [comment]
谢谢大大，您分析的很对，按照您的思路，成功了！！！
再次感谢！！！
