### ISSUE TITLE
启动应用那步很多错误，有没有配置文件要放到服务器的

### ISSUE THREAD

**Issue by xiaoliu0802** [LambdaExpression/ChinaTelecomMonitor#2]
启动应用那步很多错误，有没有配置文件要放到服务器的

**Comment by LambdaExpression** [comment]
问题1:启动应用那步很多错误
- 1.请提供当前系统信息，安装的docker版本
- 2.请提供启动命令及相关错误日志
问题2:有没有配置文件要放到服务器
- 没有，文件会自动生成

**Comment by xiaoliu0802** [comment]
./China_Telecom_Monitor_amd64 --prot 8071 --dockerProt 9222 --username 'xxx' --password 'xxx'

**Comment by xiaoliu0802** [comment]
搞好了，app设置的密码不行，这个关闭ssh后似乎没有后台运行，IP:8081无法打开，组件也更新不了数据

**Comment by LambdaExpression** [comment]
“搞好了，app设置的密码不行”，
- 恭喜你，估计你说的是密码设置错了吧

“这个关闭ssh后似乎没有后台运行”
- 虽然你说的后面几个问题都和本应用关系不大，但我都一一回复一下吧
- 应用需要保证后台运行请使用 Linux nohup 命令，相关资料可以在网上找一下

“IP:8081无法打开”
- 大概率是端口被占用或服务器防火墙拦截了，前者可以通过更换一个端口解决，后者可能需要在服务器内开放防火墙端口或在服务器的管理后台打开，这需要结合你使用的服务器运营商考虑

“组件也更新不了数据”
- 你提到的组件估计是指Scrpotable的组件吧，Scrpotable app 是有一套自己的组件刷新机制，这套刷新机制并没有提供给开发者太多的控制权。
- 不过这个组件也只是这个项目的其中一个应用场景。项目本质上是为了解决电信cookies 的24小时自动过期导致无法实时获取话费、语音、流量等信息。我个人倒希望通过为大家解决这个痛点，让大家把开发精力放在后面的其他应用开发上。
- 我在介绍中补充了接口参数说明，有需要的话，可以看一下
