### ISSUE TITLE
电信又更换了新勾选隐私协议位置

### ISSUE THREAD

**Issue by 961905** [LambdaExpression/ChinaTelecomMonitor#3]
![Uploading 2F108ED6-CC37-473C-823C-11CD4A44E90C.jpeg…]()

**Comment by LambdaExpression** [comment]
暂时可以先使用回 v1.0.0 版本。
近来工作比较忙，等我空闲下来后，再加一步自动检查判断勾选隐私协议

**Comment by LambdaExpression** [comment]
我先简单改一个版本 [China_Telecom_Monitor_amd64](https://github.com/LambdaExpression/ChinaTelecomMonitor/suites/6578297207/artifacts/246453270)，你可以暂时先试用一下

https://github.com/LambdaExpression/ChinaTelecomMonitor/actions/runs/2353084059

**Comment by 961905** [comment]
> 我先简单改一个版本 [China_Telecom_Monitor_amd64](https://github.com/LambdaExpression/ChinaTelecomMonitor/suites/6578297207/artifacts/246453270)，你可以暂时先试用一下
> 
> https://github.com/LambdaExpression/ChinaTelecomMonitor/actions/runs/2353084059

这个也可以用了

**Comment by LambdaExpression** [comment]
ok，那没什么问题，我就先把这个问题关了
