### ISSUE TITLE
一些自己需要的数据

### ISSUE THREAD

**Issue by WM9116** [LambdaExpression/ChinaTelecomMonitor#4]
您好大佬，最近研究成功运行了这个好项目，之前一直找不到电信的项目，确实难做，挺厉害的，佩服。不过，您如果以后有时间或者有兴趣，能不能麻烦您多加几个返回的数据，当然您目前的项目在您的苹果插件上完全足够，不过我是安卓党，还可以用于其他用处，所以多加入一些数据，对一些人是很有用处的，比如主套餐的名称，比如星卡什么的，通用/定向剩余量等，十分感谢！当然，还是看您自己，我只是闲聊，最后再次感谢！

**Comment by LambdaExpression** [comment]
感谢你支持。你提的需求我先记下来。因为近来工作，暂时没有太多时间和精力处理这边。等我这边没这么忙时，我再研究一下获取这些数据的可行性

**Comment by LambdaExpression** [comment]
你可以试一下这一个版本 [China_Telecom_Monitor_amd64](https://github.com/LambdaExpression/ChinaTelecomMonitor/suites/6621293550/artifacts/249398626) 。我临时最加一个 /show/detail ，这个接口的数据是从电信的 [https://e.189.cn/store/user/package_detail.do](https://e.189.cn/store/user/package_detail.do) 接口获取而来，我没有进行数据二次处理，完全是原始数据输出。
不过有个问题，我在网上没有找到电信的相关文档，电信这个接口里面有些参数值的具体含义，我也不是特别清楚，可能需要你自行研究一下

https://github.com/LambdaExpression/ChinaTelecomMonitor/actions/runs/2371783828

**Comment by WM9116** [comment]
非常感谢您的回复和工作，原始数据应该够我使用了。我会继续研究的。
