### ISSUE TITLE
超过重试次数

### ISSUE THREAD

**Issue by 961905** [LambdaExpression/ChinaTelecomMonitor#5]
有的时候会超过重试次数，无法进行登录成功，有无具体参数设置？

**Comment by LambdaExpression** [comment]
[feat(chinaTelecom.go): 优化自动适应电信登录页面](https://github.com/LambdaExpression/ChinaTelecomMonitor/actions/runs/2492645280)

这是电信登录页面改变了，导致登录失败。[China_Telecom_Monitor_amd64](https://github.com/LambdaExpression/ChinaTelecomMonitor/suites/6919357307/artifacts/268979581) 这是我刚修复的版本，你也可以先试一下

**Comment by Mrvivi** [comment]
其实我一直喜欢这类小组件，突然间我就看到这个教程的，第一次安装遇到了监听端口开不起来导致不能使用的问题，折腾了非常久的时间才弄好。刚开心用三天，发现出问题了，小组件余量都是零，好像CK失效的感觉。我来到教程发现更新了，我就删镜像重新装，可是遇到很大的麻烦，启动后ctr+c停止我发现有个这样的错误：
^C[ERRO] 2022/06/14 19:08 http: Server closed
2022-06-14T19:08:22.785+0800    error   cmd/main.go:181 InitIris errorhttp: Server closed
main.initIris
        /home/runner/work/ChinaTelecomMonitor/ChinaTelecomMonitor/cmd/main.go:181
main.main
        /home/runner/work/ChinaTelecomMonitor/ChinaTelecomMonitor/cmd/main.go:35
runtime.main
        /opt/hostedtoolcache/go/1.16.15/x64/src/runtime/proc.go:225

而且我发现启动命令（$ ./China_Telecom_Monitor_amd64 --prot 8081 --dockerProt 9222 --username '电信账号' --password '电信密码'）输完后跟我第一次安装启动的那个画面不一样。现在服务开不起来，我分析原因是端口打不开的原因，因为执行测试访问命令curl http://127.0.0.1:8081/show/flow出现curl: (7) Failed to connect to 127.0.0.1 port 8081: Connection refused，可问题是我用尽了所有方法开8081端口，最后查询8081端口依然是关闭的。可我用ufw status看到8081端口是放行了的。我重装，重启vps,把ChinaTele.service加入开机启动各种方法都试了，依然无法访问8081端口。这应该是导致我用不了主要原因，可是我不明白为什么会这样。谁能救救我。

另外，我是Linux小白，很多东西不懂，不知道如何排错。希望有人回复我。

**Comment by LambdaExpression** [comment]
> 其实我一直喜欢这类小组件，突然间我就看到这个教程的，第一次安装遇到了监听端口开不起来导致不能使用的问题，折腾了非常久的时间才弄好。刚开心用三天，发现出问题了，小组件余量都是零，好像CK失效的感觉。我来到教程发现更新了，我就删镜像重新装，可是遇到很大的麻烦，启动后ctr+c停止我发现有个这样的错误： ^C[ERRO] 2022/06/14 19:08 http: Server closed 2022-06-14T19:08:22.785+0800 error cmd/main.go:181 InitIris errorhttp: Server closed main.initIris /home/runner/work/ChinaTelecomMonitor/ChinaTelecomMonitor/cmd/main.go:181 main.main /home/runner/work/ChinaTelecomMonitor/ChinaTelecomMonitor/cmd/main.go:35 runtime.main /opt/hostedtoolcache/go/1.16.15/x64/src/runtime/proc.go:225
> 
> 而且我发现启动命令（$ ./China_Telecom_Monitor_amd64 --prot 8081 --dockerProt 9222 --username '电信账号' --password '电信密码'）输完后跟我第一次安装启动的那个画面不一样。现在服务开不起来，我分析原因是端口打不开的原因，因为执行测试访问命令curl [http://127.0.0.1:8081/show/flow出现curl](http://127.0.0.1:8081/show/flow%E5%87%BA%E7%8E%B0curl): (7) Failed to connect to 127.0.0.1 port 8081: Connection refused，可问题是我用尽了所有方法开8081端口，最后查询8081端口依然是关闭的。可我用ufw status看到8081端口是放行了的。我重装，重启vps,把ChinaTele.service加入开机启动各种方法都试了，依然无法访问8081端口。这应该是导致我用不了主要原因，可是我不明白为什么会这样。谁能救救我。
> 
> 另外，我是Linux小白，很多东西不懂，不知道如何排错。希望有人回复我。

我看了一下日志，你用的应该不是最新版本。你可以试一下执行 ./China_Telecom_Monitor_amd64 -version 看一下是不是最新的 v1.0.4 版本，如果不是的话，下载最新版本应该就可以了。如果这个命令没有正确打印版本号，那也代表使用的不是最新版本

**Comment by Mrvivi** [comment]
1. **执行命令后这样的：**
root@vultr:~#  ./China_Telecom_Monitor_amd64 -version
![1](https://user-images.githubusercontent.com/49402255/173758154-bea27a99-fa37-44e4-ad74-3da3283a0554.jpg)

2. **然后我用服务启动状态命令查看项目运行状态是这样的：**
root@vultr:~# systemctl status ChinaTele
![2](https://user-images.githubusercontent.com/49402255/173758197-410fa976-65ac-4ffc-b37c-e7cc9fd66203.jpg)

**Comment by LambdaExpression** [comment]
> * **执行命令后这样的：**
>   root@vultr:~#  ./China_Telecom_Monitor_amd64 -version
>   ![1](https://user-images.githubusercontent.com/49402255/173758154-bea27a99-fa37-44e4-ad74-3da3283a0554.jpg)
> * **然后我用服务启动状态命令查看项目运行状态是这样的：**
>   root@vultr:~# systemctl status ChinaTele
>   ![2](https://user-images.githubusercontent.com/49402255/173758197-410fa976-65ac-4ffc-b37c-e7cc9fd66203.jpg)

你现在执行的不是最新版本的应用，可以先重新下载最新的版本执行试一下

`wget https://github.com/LambdaExpression/ChinaTelecomMonitor/releases/download/v1.0.4/China_Telecom_Monitor_amd64`

**Comment by Mrvivi** [comment]
我下载的就是最新的，v1.0.4
![1](https://user-images.githubusercontent.com/49402255/173764562-1998c7d0-e3c1-46b4-87e6-7c500ecc0ae9.jpg)
依然是一模一样的问题，还有办法解决吗
![2](https://user-images.githubusercontent.com/49402255/173764646-f6a82cb1-ae00-4f73-b9d3-eec6d3ad448b.jpg)

**Comment by LambdaExpression** [comment]
> 我下载的就是最新的，v1.0.4 ![1](https://user-images.githubusercontent.com/49402255/173764562-1998c7d0-e3c1-46b4-87e6-7c500ecc0ae9.jpg) 依然是一模一样的问题，还有办法解决吗 ![2](https://user-images.githubusercontent.com/49402255/173764646-f6a82cb1-ae00-4f73-b9d3-eec6d3ad448b.jpg)

命令暂时不支持 -v ，需要完整的 -version

**Comment by LambdaExpression** [comment]
启动30秒后还是无法正常使用吗？有错误日志吗？

**Comment by Mrvivi** [comment]
-v和-version都用过 ， 结果是一模一样的 。 日志在哪里看呢 
几分钟了都无法使用，我用测试访问地址访问，如下：
![1](https://user-images.githubusercontent.com/49402255/173769576-6086e159-de87-4fd4-994c-5f89d1b85dc0.jpg)

但是8081端口我用ufw命令开了的

**Comment by LambdaExpression** [comment]
> ufw

![image](https://user-images.githubusercontent.com/17667040/173773922-5c87bf82-89f2-40e3-aad0-74088edea9f2.png)

1. 版本信息，我想再确认一下。 -version 打印的信息，不是上图的版本信息？
```
Version: v1.0.4
Go Version: go version go1.16.15 linux/amd64
Git Commit: 2342a2b5e23342dc40032725c641d4e390ab2d99
Build Time: 2022-06-14 03:06:15
```

2.日志位置可以通过启动时追加 `--dataPath  '指定日志保存目录'`，完整命令 `./China_Telecom_Monitor_amd64 --prot 8081 --dockerProt 9222 --username '电信账号' --password '电信密码' --dataPath  '指定日志保存目录'` 

![image](https://user-images.githubusercontent.com/17667040/173775565-048d959d-6123-4d79-89e3-45df779f5079.png)

**Comment by LambdaExpression** [comment]
> 我下载的就是最新的，v1.0.4 ![1](https://user-images.githubusercontent.com/49402255/173764562-1998c7d0-e3c1-46b4-87e6-7c500ecc0ae9.jpg) 依然是一模一样的问题，还有办法解决吗 ![2](https://user-images.githubusercontent.com/49402255/173764646-f6a82cb1-ae00-4f73-b9d3-eec6d3ad448b.jpg)

![image](https://user-images.githubusercontent.com/17667040/173776709-91fc33ae-6d8b-49f0-9fc8-6010756a8e3a.png)

你的文件下载回来后自动命名为 `China_Telecom_Monitor_amd64.5` 了，不是 `China_Telecom_Monitor_amd64` ，你检查一下是不是这个原因

**Comment by Mrvivi** [comment]
**是的，确定-version打印出来跟你结果不一样，如下：**
![1](https://user-images.githubusercontent.com/49402255/173790450-312bd0da-e98e-46eb-8203-1fa1e28549c9.jpg)

**你眼睛太尖了，这一说我就发现了，确实是的，我又下载一遍他变成了64.6了，我去！！** 
![2](https://user-images.githubusercontent.com/49402255/173790771-4cb115d8-f95d-448a-a954-78fd03ca5160.jpg)

[stdout.log](https://github.com/LambdaExpression/ChinaTelecomMonitor/files/8907859/stdout.log)
上面是日志文件，你帮我看看吧，我太难了

**Comment by Mrvivi** [comment]
删除了，重新下载安装并授予权限后启动了，真的可以了。我终于知道之前为什么无法运行了，因为启动后我看跑起来了就直接ctrl+c结束了，然后我就直接去小组件填写项目远程访问地址  http://xxxxx/show/flow  发现又不行了。
经过测试，我才知道启动后不能ctrl+c停止它，必须让他一直运行在那里，可是我得关VPS啊，我还得干其他东西啊，是我停止的方式不对吗？不应该用ctrl+c命令吗？还是说怎么办呢？ 求答案

**Comment by LambdaExpression** [comment]
> 删除了，重新下载安装并授予权限后启动了，真的可以了。我终于知道之前为什么无法运行了，因为启动后我看跑起来了就直接ctrl+c结束了，然后我就直接去小组件填写项目远程访问地址 http://xxxxx/show/flow 发现又不行了。
> 经过测试，我才知道启动后不能ctrl+c停止它，必须让他一直运行在那里，可是我得关VPS啊，我还得干其他东西啊，是我停止的方式不对吗？不应该用ctrl+c命令吗？还是说怎么办呢？ 求答案

你可以学习一下，Linux的 nohup 命令，保证服务在后台运行不挂断。

nohup ./China_Telecom_Monitor_amd64 --prot 8081 --dockerProt 9222 --username '电信账号' --password '电信密码' --dataPath '指定日志保存目录' >/dev/null &

**Comment by Mrvivi** [comment]
好吧 ，原来还需要这样让它后台运行下，终于解决了我的困扰。我说怎么之前我安装了无数遍，只要ctrl+c退出后就无法运行了。比如我找到了日志文件，那我替换'指定日志保存目录'='/root/data/log'还是'/root/data'  
![Snipaste_2022-06-16_13-33-03](https://user-images.githubusercontent.com/49402255/173998465-933babbf-480b-4855-b496-91b8260b2b06.jpg)

**Comment by LambdaExpression** [comment]
> 好吧 ，原来还需要这样让它后台运行下，终于解决了我的困扰。我说怎么之前我安装了无数遍，只要ctrl+c退出后就无法运行了。比如我找到了日志文件，那我替换'指定日志保存目录'='/root/data/log'还是'/root/data' ![Snipaste_2022-06-16_13-33-03](https://user-images.githubusercontent.com/49402255/173998465-933babbf-480b-4855-b496-91b8260b2b06.jpg)

看你的截图日志目录结构是 '指定日志保存目录'=‘/root/data’，不过这种日志目录并没有任何限制要求，按你自己的使用习惯就好了

**Comment by Mrvivi** [comment]
好的，兄的。 感谢你的时间，所有问题已经解决，希望项目可持续使用。最后顺便问下，能搞中国移动的吗  ？

**Comment by LambdaExpression** [comment]
> 好的，兄的。 感谢你的时间，所有问题已经解决，希望项目可持续使用。最后顺便问下，能搞中国移动的吗 ？

谢谢，你的支持。手上没有中国移动账号，暂时没有中国移动的计划。

**Comment by Mrvivi** [comment]
好的，我明白了。你若一直在 我便一直用

**Comment by LambdaExpression** [comment]
请问还有其他问题吗？没有的话，我就先把问题 close 了

**Comment by Mrvivi** [comment]
没有问题了，一切正常中 。可以关了
