### ISSUE TITLE
总是提示无法连接到

### ISSUE THREAD

**Issue by LitPrompt** [LambdaExpression/ChinaTelecomMonitor#7]
![image](https://user-images.githubusercontent.com/72721151/175050884-c5495b4a-bf75-4ac7-afe8-0f85ab9d4724.png)

**Comment by QGCliveDavis** [comment]
用的是1.04的，chmod也给权限了，而且也没有重复下载China_Telecom_Monitor_amd64，但是运行不了，希望能指点一下
