### ISSUE TITLE
多次请求后掉登录

### ISSUE THREAD

**Issue by YANZIYA** [LambdaExpression/ChinaTelecomMonitor#9]
您好，我利用您项目调用在机器人上使用，项目多次请求返回数据后会掉登录这期间需要等10分钟或者5分钟后重新执行命令才可以正常获取数据，但是期间浏览器访问天翼都正常，这是不是ua问题呢

**Comment by LambdaExpression** [comment]
如果没有修改默认启动参数，电信登录cookie失效后需要距离上次登录12小时后，才会再次执行登录。如果是短时间访问的数据都不是最新的数据，那应该是和 --intervalsTime 配置有关。

[应用支持启动参数](https://github.com/LambdaExpression/ChinaTelecomMonitor#%E8%A1%A5%E5%85%85)
![image](https://user-images.githubusercontent.com/17667040/175846502-698f5d83-5d6e-4bf4-afd0-d5d8236f95fe.png)


--loginIntervalTime 电信登录间隔时间，这个主要是为了防止频繁登录产生被封号风险。默认设置为12小时，可以自行降低时间间隔
--intervalsTime     接口防止重刷时间，和接口缓存时间一个概念，也是一个为了防止电信封号的参数，默认时间3分钟。例如：12:00访问一次后，12:00至12:03访问，都会返回12:00产生缓存，12:03 01才会重新请求电信接口。


因为项目是开源的，所以这两个涉及账号安全的配置时间会设置的比较保守，你可以先试一下适当降低这两个参数看看。
不过这个和你提到的“掉登录”、“10分钟或者5分钟”，并不完全吻合，如果你测试之后仍然有问题，可以提供一些应用日志，让我检查一下吗

**Comment by YANZIYA** [comment]
你好这是相关的日志
![01](https://user-images.githubusercontent.com/104676233/175866518-7f063e89-6308-4f26-96ac-b38a376c17b6.png)
[stdout.log](https://github.com/LambdaExpression/ChinaTelecomMonitor/files/8988894/stdout.log)

**Comment by YANZIYA** [comment]
你好，我在目录生成了cookie.go后登录成功

**Comment by YANZIYA** [comment]
第二点，我看登录的时候发现提示cookie.go缺失，我手动生成后，即可登录获取数据

**Comment by LambdaExpression** [comment]
看你的描述感觉有点像是应用缺少 cookie.json 文件的创建权。
应用首次启动时，会报 cookie.json 文件缺失，但只要登录成功了一次后，应用就会自动执行创建 cookie.json 文件
